# Generated by Django 6.0.1 on 2026-02-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_category_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video',
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(default=1, help_text='Youtube video URL'),
            preserve_default=False,
        ),
    ]
