# Generated by Django 6.0.1 on 2026-02-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_video_project_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video_url',
        ),
        migrations.AddField(
            model_name='project',
            name='vimeo_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
